### ISSUE TITLE
ESP12F is now a "standard assembly only" part on JLCPCB

### ISSUE THREAD

**Issue by Caseritto** [Sorakage033/SlimeVR-CheeseCake#18]
![image](https://github.com/user-attachments/assets/d8ac6260-a986-4eb2-ae86-74696208f37f)
![image](https://github.com/user-attachments/assets/64d9408b-8023-4fb9-9172-43fce860cdcf)

As the title states, this steeply increases the cost of JLCPCB assembly as "economic assembly" is no longer an option with this part in the component list.

Any possible solutions or do we just have to bear the added cost now?

**Comment by Sorakage033** [comment]
It’s possible that ESP-12F is no longer supported because it may get damaged under economic PCBA. Here are three solutions:

1. Since ESP-12F is not too difficult to solder, if you have a soldering iron or heat plate, you might choose to skip PCBA assembly and assemble it yourself (though this may require extra time).
   
2. There are still ESP-12F modules that can be used with economic PCBA, such as C784365 or C19949064. However, these are generally out of stock. You can use global sourcing or similar options to purchase them and have them sent to your personal warehouse at JLCPCB, then select them as replacements during PCBA.

3. Based on feedback from many DIY enthusiasts, using economic PCBA assembly can increase the DOA (Dead on Arrival) rate, with extreme cases reporting a DOA rate as high as 20/30. So if you are unable to repair PCBs yourself, it’s better to opt for standard PCBA, which will save you from a lot of hassle.

**Comment by Caseritto** [comment]
Appreciate the response, will look into all available options
